# Rules of Engagement

If technology is going to *help* with access to a conference, it is crucially important to put together an engagement plan.

10 key questions:

(1) What modes of communication will delegates be using? Email? Audio? Twitter? Instagram? Facebook? 

(2) (how) Can you use those channels for engagement that improves access and quality of engagement?

(3) Who will monitor channels and provide engagement? Can a person meaningfully engage with multiple streams concurrently?

(5) What are the ground-rules for participation? (e.g. should one person be allowed monopolise the discussion? do you want to have some mode of deference in place to particular participants? what kinds of behaviour might affect the experience of others and thus be discouraged? what kids of behaviour might help the experience of others and thus be encouraged? are there specific types of participation - on topic, off topic, etc. which have different priority in discussion?)

(4) Who will communicate and enforce the ground-rules for your session?